
services:
  nginx:
    build:
      dockerfile: ./nginx/nginx.Dockerfile
    container_name: reverse_proxy
    expose:
      - "80"
    ports:
      - "8080:80"
    restart: always

    depends_on:
      - api

  api:
    build: .

    container_name: api

    environment:
      - CIVETWEB_DATABASE_PATH=/app/data/db.json
      - CIVETWEB_DOCUMENT_ROOT=/app/static
      - CIVETWEB_PORT=8080
        
    volumes:
      - ./data:/app/data
